-- initial user data
INSERT INTO USER VALUES(101, SYSDATE(), 'Aaryan');
INSERT INTO USER VALUES(102, SYSDATE(), 'Vinit');
INSERT INTO USER VALUES(103, SYSDATE(), 'Vishnu');
INSERT INTO USER VALUES(104, SYSDATE(), 'Ajay');
INSERT INTO USER VALUES(105, SYSDATE(), 'Riya');

 -- initial posts data
INSERT INTO POST VALUES(5001, 'First post', 104);
INSERT INTO POST VALUES(5002, 'First post', 105);
INSERT INTO POST VALUES(5003, 'First post', 102);
INSERT INTO POST VALUES(5004, 'Second post', 104);